sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tLtT21Zjyt1W85PpzfT
    accessKeySecret: whXzZlEqsxy5fJRSZ0F1xpXFTsqKmd
    bucketName: zkx-tlias